### ISSUE TITLE
Can't read .py files and keeps showing 'Binary file, content not displayed'

### ISSUE THREAD

**Issue by sungwo101** [seeschweiler/contextforge#5]
I'm trying to use your project, but I keep running into this issue where it's not reading the code inside .py or .ipynb files. All I get is this message: 
'Binary file, content not displayed.'

Shouldn't it be able to read .py files at least? Any ideas on how to fix this? Thanks

**Comment by seeschweiler** [comment]
Hi, thanks for reaching out.

That's strange. I tested it with *.py files and on my system (Mac) it is running as expected. 

What you can do: Check the encoding of your .py and .ipynb files. Ensure they're saved with UTF-8 encoding. On which OS are you running ContextForge? Which Python version?

**Comment by seeschweiler** [comment]
You can also adapt the is_binary function for a quick test and let it return `False` for py files in any case:
```
def is_binary(file_path):
    """Check if a file is binary."""
    if file_path.endswith(('.py', '.ipynb')):
        return False
    try:
        with open(file_path, 'tr') as check_file:
            check_file.read()
            return False
    except:
        return True
```

**Comment by sungwo101** [comment]
Thanks, Turns out my files were encoded in ASCII.
Once I fixed that part you mentioned, it's now working correctly.
